### ISSUE TITLE
RPush in a multi-tenant app not sending messages...

### ISSUE THREAD

**Issue by MSeneadza** [rpush/rpush#433]
I'm using Rpush in an app that also uses the Apartment gem to manage multi-tenancy on Postgresql.  Apartment essentially changes the target Postgres schema for ActiveRecord so the queries access the correct tables (schema) for the current tenant.  

In my case, I have tenants (and Postgres schemas) by country.  The US is my default (which aligns to my 'public' Postgres schema).  

I have Rpush tables in every tenant's schema and I'm sending notifications from background jobs, which are tenant-specific.  So, I'll switch to the US tenant and send its notifications.  Then switch to the UK tenant and send its notifications, etc.

What I'm experiencing is that Rpush notifications are only being sent for the US (public schema).  After some poking around I decided to try a test from a Rails console.  I created a notification in the US/public schema, then switched to the UK tenant and issued `Rpush.push` .  Sure enough, the notification from the US tenant got sent.  

So it seems that Rpush is ignoring the current schema set by the Apartment gem.  I'm wondering if there's a way to get Rpush to respect the target schema set by Apartment.

I think I know of a workaround -- Apartment allows you to set certain tables to be across all tenants.  So I *could* set the `rpush_notifications` table to be common to all tenants but I've yet to think through the downsides to that.

Any input is greatly appreciated.

**Comment by zia954** [comment]
I am having same issue, i need to switch back and forth to access public schema

**Comment by troya2** [comment]
I have implemented this with apartment and added Rpush::App, Rpush::Notification, Rpush::Apns::Feedback models to Apartment's config.excluded_models array.  You can set up two Rpush::App records for each tenant (production and sandbox) and use them to push on behalf of each tenant. 

The up side is that it doesn't require any patching of rpush to work with Apartment.  The down side is that all notifications are in one table for all tenants.  Perhaps there is a way to shard the data based on the Rpush::App id if keeping the data physically separate for each tenant is a requirement.

**Comment by zia954** [comment]
this is still an issue, i am just switching the schema to public schema whenever i have to send push notification
