### ISSUE TITLE
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0

### ISSUE THREAD

**Issue by anton-co** [rpush/rpush#639]
When using Redis version 4.6 I get this error:

```
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.multi do
  redis.get("key")
end

should be replaced by

redis.multi do |pipeline|
  pipeline.get("key")
end

(called from /usr/local/bundle/gems/rpush-7.0.1/lib/rpush/client/redis/notification.rb:70:in `block in register_notification'}
```

**Comment by benlangfeld** [comment]
I'm planning to work on a fix here. I'm starting with https://github.com/rpush/modis/pull/35 and https://github.com/rpush/modis/pull/34. Once modis is entirely free of deprecation warnings I will address rpush.

**Comment by benlangfeld** [comment]
@anton-co Can you clarify which versions of rpush, modis and redis (the gem) you are using?

**Comment by benlangfeld** [comment]
I think your issue was fixed by modis v4.0.1. Could you try again with that version, ensuring that you do not upgrade past redis v4.7.1?

**Comment by benlangfeld** [comment]
Modis v4.1.0 was released with fixes for several more deprecation warnings. An upgrade is recommended.

**Comment by bucknermr** [comment]
I'm also still seeing this issue on `4.2` and `redis 4.8.1`, but I think I've found the issue.

In `Rpush::Client::Redis::Notification`, there is the following `after_create` callback, which calls `zadd` on a Redis instance:

https://github.com/rpush/rpush/blob/eb48a90241f5de32103c394aefcd88c88491ede4/lib/rpush/client/redis/notification.rb#L9
https://github.com/rpush/rpush/blob/eb48a90241f5de32103c394aefcd88c88491ede4/lib/rpush/client/redis/notification.rb#L68-L72

However, in `Modis::Persistence`, registered callbacks for saving a record are executed _within_ a transaction (or `#multi` block): https://github.com/rpush/modis/blob/bfe2b160d59541223541e4195532de465513800e/lib/modis/persistence.rb#L212-L215
(Note that #destroy has the [same issue](https://github.com/rpush/modis/blob/bfe2b160d59541223541e4195532de465513800e/lib/modis/persistence.rb#L137-L140))

At a glance, it seems there are at least two ways forward:
1. Have `Modis` keep a reference to a `current_transaction`, and ensure that any calls to Redis use either the `current_transaction`, or if not in a transaction, then use a client from the pool.
2. Update `Modis::Persistence` so that callbacks are executed outside of the transaction.

Neither of these seem ideal, though someone with more context might understand better than I. For option 1, the caller would need to know that the callback is executed within a transaction and prevent calling certain methods. For option 2, you lose the atomicity of the `after_create` callback.

**Comment by J-Swift** [comment]
We are also running into this with

modis 4.3.2
redis 4.8.1

wondering if there was ever a fix upstreamed?
